universe = container
container_image = docker://staphb/spades:4.2.0

executable = spades_one_sample.sh

arguments = $(request_cpus)

transfer_input_files = reads/ERR2653804_R1.fastq.gz, reads/ERR2653804_R2.fastq.gz

log = logs/assembly_ERR2653804.log
error = logs/assembly_ERR2653804.err
output = logs/assembly_ERR2653804.out

want_campus_pools = true
want_ospool = true

request_cpus = 16
request_memory = 16GB
request_disk = 10GB    

queue
