universe = container
container_image = docker://staphb/spades:4.2.0

executable = spades.sh
arguments = $(request_cpus) $(sample)

transfer_input_files = reads/$(sample)_R1.fastq.gz, reads/$(sample)_R2.fastq.gz

log = logs/assembly_$(sample).log
error = logs/assembly_$(sample).err
output = logs/assembly_$(sample).out

want_campus_pools = true
want_ospool = true

request_cpus = 16
request_memory = 16GB
request_disk = 10GB

retry_request_memory = 32GB, 64GB

queue sample from (
#	ERR2653804
	ERR2653803
	ERR2653802
	ERR2653801
)
